name: 'Terraform Plan APply'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  terraform-tplan:
    name: 'Terraform-Plan'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Login to Azure using secrets
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Generate Terraform execution plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan

    # Save Terraform Plan as Artifact
    - name: Save Terraform Plan as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: tfplan 
  terraform-apply:
    name: 'Terraform-Apply'
    runs-on: ubuntu-latest
    needs: [terraform-tplan]

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Login to Azure using secrets
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
    
    # Download saved plan from Artifacts
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
          name: tfplan
         # path: tfplan.out

    #Terraform Apply
    - name: Apply Terraform Plan
      run: terraform apply -auto-approve tfplan
